services:
  clash:
    build: .
    container_name: clash
    ports:
      # export http_proxy=http://127.0.0.1:7890 https_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7891
      - "7890:7890"  # HTTP Proxy Port
      - "7891:7891"  # SOCKS5 Proxy Port

      # export http_proxy=http://127.0.0.1:7891 https_proxy=http://127.0.0.1:7891 all_proxy=socks5://127.0.0.1:7891
      # - "7891:7891"  # Mixed (HTTP + SOCKS5) Port

      - "9090:9090"  # Dashboard or API Port
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      - ./ui_pages:/root/.config/clash/ui_pages
    restart: unless-stopped

  #  ✘ dashboard Error Get "https://registry-1.docker.io/v2/": net/http: request canceled while...                 18.5s
  # Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  # dashboard:
  #   image: haishanh/yacd
  #   container_name: yacd
  #   ports:
  #     - "1234:80"  # Expose YACD on port 1234
  #   depends_on:
  #     - clash
  #   restart: unless-stopped

  # dashboard:
  #   build:
  #     context: ./hinak0_yacd
  #     args:
  #       TARGETPLATFORM: linux/amd64
  #       BUILDPLATFORM: linux/amd64
  #   container_name: yacd
  #   ports:
  #     - "1234:80"  # Expose YACD on port 1234
  #   depends_on:
  #     - clash
  #   restart: unless-stopped
